---
- name: Check file diff
  hosts: all
  gather_facts: false

  tasks:

    - name: Grab Repo with source file
      run_once: true
      ansible.builtin.git:
        repo: "{{ sourcefilerepo }}"
        dest: /tmp/demo
        accept_hostkey: true
        force: true

    - name: Check for variance in File
      check_mode: true
      diff: true
      register: filechanges
      ansible.builtin.copy:
        src: "/tmp/demo/{{ file2comp }}"
        dest: "/etc/{{ file2comp }}"
        mode: '0644'

    - name: Stat check_mode
      when: filechanges.changed == true
      register: statvar
      ansible.builtin.stat:
        path: "/etc/{{ file2comp }}"
