---
- name: Win_disk_facts from docs.ansible.com
  hosts: all
  
  tasks:

    - name: Get disk facts
      community.windows.win_disk_facts:

    - name: Output first disk size
      debug:
        var: ansible_facts.disks[0].size

    - name: Convert first system disk into various formats
      debug:
        msg: '{{ disksize_gib }} vs {{ disksize_gib_human }}'
      vars:
        # Get first system disk
        disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'

        # Show disk size in Gibibytes
        disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'   # returns "223.6 GiB" (human readable)
        disksize_gib: '{{ (disk.size/1024|pow(3))|round|int }} GiB'  # returns "224 GiB" (value in GiB)

        # Show disk size in Gigabytes
        disksize_gb_human: '{{ disk.size|filesizeformat }}'        # returns "240.1 GB" (human readable)
        disksize_gb: '{{ (disk.size/1000|pow(3))|round|int }} GB'  # returns "240 GB" (value in GB)

    - name: Output second disk serial number
      debug:
        var: ansible_facts.disks[1].serial_number
