---
- name: Check file diff
  hosts: rheldemo
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Check the sshd_config file
      register: filechanges
      diff: true
      when:
      ansible.builtin.copy:
        src: "{{ file2comp }}"
        dest: "/etc/ssh/{{ file2comp }}"
        mode: '0600'
        group: root
        owner: root
        seuser: system_u
        serole: object_r
        setype: etc_t
        selevel: s0

    - name: Print
      debug:
        var: filechanges

  handlers:

    - name: Stat check_mode
      when: filechanges.changed equalto true
      ansible.builtin.stat:
        path: "/etc//ssh/{{ file2comp }}"
